[package]
name = "metrics-benchmark"
version = "0.1.1-alpha.5"
authors = ["Toby Lawrence <toby@nuclearfurnace.com>"]
edition = "2018"
rust-version = "1.56.1"
publish = false

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
getopts = "0.2"
hdrhistogram = { version = "7.2", default-features = false }
quanta = "0.10.0"
portable-atomic = "0.3"
metrics = { version = "^0.20", path = "../metrics" }
metrics-util = { version = "^0.14", path = "../metrics-util" }
