[package]
name = "metrics-benchmark"
version = "0.1.1-alpha.5"
authors = ["Toby Lawrence <toby@nuclearfurnace.com>"]
edition = "2018"
publish = false

[dependencies]
log = "0.4"
env_logger = "0.8"
getopts = "0.2"
hdrhistogram = { version = "7.2", default-features = false }
quanta = "0.8"
atomic-shim = "0.1"
metrics = { version = "^0.16", path = "../metrics" }
metrics-util = { version = "^0.9", path = "../metrics-util" }
