[workspace]
members = [
  "metrics",
  "metrics-macros",
  "metrics-util",
  "metrics-exporter-tcp",
  "metrics-exporter-prometheus",
  "metrics-tracing-context",
  "metrics-observer",
  "metrics-benchmark",
]

[profile.release]
debug = true