sign-commit = true
sign-tag = true
pre-release-replacements = [
  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}"},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n\n## [Unreleased] - ReleaseDate"},
  {file="RELEASES.md", search="Unreleased", replace="{{version}}"},
  {file="RELEASES.md", search="ReleaseDate", replace="{{date}}"},
  {file="RELEASES.md", search="<!-- next-header -->", replace="<!-- next-header -->\n\n## [Unreleased] - ReleaseDate\n\n- No notable changes."},
]
